openapi: 3.0.3
info:
  title: ComfyUI MCP Tools
  description: |
    Built-in MCP tools for ComfyUI operations.
    These tools are automatically registered when AgentX starts.
  version: 1.0.0

servers:
  - url: mcp://comfyui
    description: Internal MCP server

tags:
  - name: workflow
    description: Workflow read/write operations
  - name: nodes
    description: Node search and installation
  - name: execution
    description: Workflow execution and monitoring
  - name: models
    description: Model management

paths:
  # ==================== Workflow Tools ====================

  /tools/get_workflow:
    post:
      tags: [workflow]
      summary: Get current workflow
      description: |
        Retrieves the current ComfyUI workflow JSON from the canvas.
        Returns complete workflow structure with nodes, connections, and parameters.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Workflow retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflow:
                    type: object
                    description: Complete workflow JSON
                    example:
                      nodes:
                        - id: "1"
                          type: "KSampler"
                          params: {...}
                      connections: [...]
                  version:
                    type: string
                    description: ComfyUI version
                    example: "1.0.0"

  /tools/update_workflow:
    post:
      tags: [workflow]
      summary: Update current workflow
      description: |
        Replaces the current workflow with provided JSON.
        Creates a checkpoint before modification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [workflow_data]
              properties:
                workflow_data:
                  type: string
                  description: Serialized workflow JSON
                description:
                  type: string
                  description: Checkpoint description
                  example: "Fixed sampler parameters"
      responses:
        '200':
          description: Workflow updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  checkpoint_id:
                    type: string
                    description: Created checkpoint ID
                  status:
                    type: string
                    enum: [success]

  /tools/modify_node:
    post:
      tags: [workflow]
      summary: Modify specific node parameters
      description: |
        Updates parameters of a specific node without replacing entire workflow.
        Safer than update_workflow for targeted changes.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [node_id, parameters]
              properties:
                node_id:
                  type: string
                  description: Node ID in workflow
                  example: "7"
                parameters:
                  type: object
                  description: Key-value pairs of parameters to update
                  example:
                    steps: 30
                    cfg: 7.5
      responses:
        '200':
          description: Node modified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  node_id:
                    type: string
                  updated_params:
                    type: object
                  status:
                    type: string

  /tools/get_workflow_diff:
    post:
      tags: [workflow]
      summary: Compare two workflows
      description: |
        Returns diff between two workflow versions.
        Useful for explaining changes to user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [workflow_a, workflow_b]
              properties:
                workflow_a:
                  type: string
                  description: First workflow JSON (serialized)
                workflow_b:
                  type: string
                  description: Second workflow JSON (serialized)
      responses:
        '200':
          description: Diff computed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  added_nodes:
                    type: array
                    items:
                      type: string
                  removed_nodes:
                    type: array
                    items:
                      type: string
                  modified_nodes:
                    type: array
                    items:
                      type: object
                      properties:
                        node_id:
                          type: string
                        changes:
                          type: object

  # ==================== Node Tools ====================

  /tools/search_nodes:
    post:
      tags: [nodes]
      summary: Search for nodes
      description: |
        Searches ComfyUI node registry by keyword.
        Returns matching node types with descriptions.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [query]
              properties:
                query:
                  type: string
                  description: Search keyword
                  example: "sampler"
                category:
                  type: string
                  description: Filter by category
                  example: "sampling"
                limit:
                  type: integer
                  description: Max results
                  default: 10
      responses:
        '200':
          description: Search completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodes:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: "KSampler"
                        category:
                          type: string
                          example: "sampling"
                        description:
                          type: string
                        inputs:
                          type: object
                        outputs:
                          type: object

  /tools/get_node_info:
    post:
      tags: [nodes]
      summary: Get detailed node information
      description: |
        Returns complete schema for a specific node type.
        Includes input/output types, default values, constraints.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [node_type]
              properties:
                node_type:
                  type: string
                  description: Node class name
                  example: "KSampler"
      responses:
        '200':
          description: Node info retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  node_type:
                    type: string
                  category:
                    type: string
                  description:
                    type: string
                  input_types:
                    type: object
                    description: Input schema
                  output_types:
                    type: array
                    description: Output types
                  defaults:
                    type: object
                  required_extensions:
                    type: array
                    items:
                      type: string

  /tools/install_node:
    post:
      tags: [nodes]
      summary: Install missing custom node
      description: |
        Installs a custom node package via git clone.
        Requires restart for nodes to become available.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [node_name]
              properties:
                node_name:
                  type: string
                  description: Node identifier
                  example: "ComfyUI-Impact-Pack"
                repository_url:
                  type: string
                  description: Git repository URL (optional, auto-detected if omitted)
                  example: "https://github.com/ltdrdata/ComfyUI-Impact-Pack"
      responses:
        '200':
          description: Installation started
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [installing, success, failed]
                  message:
                    type: string
                  restart_required:
                    type: boolean

  # ==================== Execution Tools ====================

  /tools/run_workflow:
    post:
      tags: [execution]
      summary: Execute current workflow
      description: |
        Queues the current workflow for execution.
        Returns prompt_id for monitoring progress.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                workflow:
                  type: string
                  description: Override workflow JSON (if not provided, uses current)
      responses:
        '200':
          description: Workflow queued
          content:
            application/json:
              schema:
                type: object
                properties:
                  prompt_id:
                    type: string
                    description: Execution ID for monitoring
                    example: "abc123-def456"
                  status:
                    type: string
                    enum: [queued]

  /tools/get_execution_status:
    post:
      tags: [execution]
      summary: Check workflow execution status
      description: |
        Returns current status of a queued/running workflow.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [prompt_id]
              properties:
                prompt_id:
                  type: string
                  description: Execution ID from run_workflow
      responses:
        '200':
          description: Status retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  prompt_id:
                    type: string
                  status:
                    type: string
                    enum: [queued, running, success, failed]
                  progress:
                    type: integer
                    description: Percentage complete (0-100)
                  current_node:
                    type: string
                    description: Currently executing node ID

  /tools/get_logs:
    post:
      tags: [execution]
      summary: Get execution logs
      description: |
        Retrieves error logs and console output for debugging.
        Filters by prompt_id or time range.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt_id:
                  type: string
                  description: Filter by execution ID
                level:
                  type: string
                  enum: [error, warning, info, debug]
                  default: error
                limit:
                  type: integer
                  default: 100
      responses:
        '200':
          description: Logs retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  logs:
                    type: array
                    items:
                      type: object
                      properties:
                        timestamp:
                          type: string
                          format: date-time
                        level:
                          type: string
                        message:
                          type: string
                        node_id:
                          type: string
                          nullable: true
                        prompt_id:
                          type: string
                          nullable: true

  /tools/cancel_execution:
    post:
      tags: [execution]
      summary: Cancel running workflow
      description: |
        Stops a currently executing workflow.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [prompt_id]
              properties:
                prompt_id:
                  type: string
      responses:
        '200':
          description: Cancellation requested
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [cancelled]

  # ==================== Model Tools ====================

  /tools/list_models:
    post:
      tags: [models]
      summary: List available models
      description: |
        Returns all models in ComfyUI model directories.
        Grouped by type (checkpoints, loras, vaes, etc.)
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                model_type:
                  type: string
                  description: Filter by model type
                  enum: [checkpoints, loras, vaes, controlnets, upscale_models, embeddings]
      responses:
        '200':
          description: Model list retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  models:
                    type: object
                    description: Models grouped by type
                    example:
                      checkpoints:
                        - "sd_xl_base_1.0.safetensors"
                        - "v1-5-pruned-emaonly.ckpt"
                      loras:
                        - "add_detail.safetensors"

  /tools/get_model_info:
    post:
      tags: [models]
      summary: Get model metadata
      description: |
        Returns metadata for a specific model file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [model_path]
              properties:
                model_path:
                  type: string
                  description: Relative path to model file
                  example: "checkpoints/sd_xl_base_1.0.safetensors"
      responses:
        '200':
          description: Model info retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  path:
                    type: string
                  size_mb:
                    type: number
                  hash:
                    type: string
                    description: SHA256 hash
                  metadata:
                    type: object
                    description: Embedded metadata (if available)

  /tools/download_model:
    post:
      tags: [models]
      summary: Download model from URL
      description: |
        Downloads a model file to ComfyUI model directory.
        Returns download progress updates.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [url, model_type]
              properties:
                url:
                  type: string
                  description: Download URL
                  example: "https://huggingface.co/..."
                model_type:
                  type: string
                  enum: [checkpoints, loras, vaes, controlnets, upscale_models, embeddings]
                filename:
                  type: string
                  description: Override filename (optional)
      responses:
        '200':
          description: Download started
          content:
            application/json:
              schema:
                type: object
                properties:
                  download_id:
                    type: string
                  status:
                    type: string
                    enum: [downloading, completed, failed]
                  progress:
                    type: integer
                    description: Percentage (0-100)
                  path:
                    type: string
                    description: Final model path (when completed)

components:
  schemas:
    # Reusable error schema
    ToolError:
      type: object
      required: [error]
      properties:
        error:
          type: string
        code:
          type: string
        details:
          type: object
